#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided. Please provide a bucket name eg. <bucket-name>"
    exit 1
fi

BUCKET_NAME=$1
echo "Listing objects in bucket \"$BUCKET_NAME\""

# List objects: https://docs.aws.amazon.com/cli/latest/reference/s3api/list-objects.html
aws s3api list-objects \
--bucket $BUCKET_NAME \
--query "Contents[].Key"