#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided. Please provide a bucket name: <bucket-name>"
    exit 1
fi

if [ -z "$2" ]; then
    echo "No filename provided. Please provide a filename: <filename>"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

echo "Uploading $FILENAME to $BUCKET_NAME/$OBJECT_KEY"

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY